sudo: required
service:
- docker
env:
  global:
  - secure: fPlG7Uvvj7vJDA0FuT6q8azHRQdQi9O+diLQiMr3l00jubVM5E+fkUaMKCukI0dmG2qwCQf5RJUDeocRV7aVwDSuafCj750v4XIlnPcgCUngTL0l76Z+NGzzDtWkNXPjcN7bPDw4V46Gd3FR8MDZkosHfD2BvQob2a6YuxXNxTZPzSu5xPU1xGjWaA/ttxk5dkmbiWdWLI+ibOCSo6e6+GiU21HWUPc4BH8uZAHdnCqLfyEZv+k0FGTByGidvJXRG91n+oja1QybGVJNElh26AeirZsGdro2YmGERLRlo8flSNE72yQdd0DYYYtgGl04jp5FLlUNjvBPYPfUaNReL7rFrr9G6sVhK0wXEBAZ5uQ5bdDZQzhROmV2Q3erVrl5QOhwgDqS6tzZIaJlXvewi0mm/IBiEM0ckeiCg0MdbRmKjgo2iqbHNVCd/TEiONyTBhtN1anq8vyOgZzFr+aXXOLzPNN9NmdFcoFe58g5fgkrg3tEUZJXdwTylnLPp0wLv14gTQfU5MAq7g5l4C+IojL5LGelkFNod/vYKyKIJWntkieStObgXXjbViFDSBMjMjKk7k815O1QAYgLio/S2UN3+C5U9ky5dJugthuoaWfWQ211YfV0Cm4jiJeVYukgVea+M1M7/ySdh1RDaCinWh+Z4eFSptuE0GEK3VbzGrc=
  - secure: DJHRTqpPiWOB7GdG2IB1YC4DkRxUMwXre7Cje+UAyH8U3Ec2XDAnOUmxBZr2io08Jtiip+xlqK4RZcZSzt3Wc8FhmtRbnTOxtRxAcHMW1MBjIC4AH0g/Cu/rP0mqWZBdOb55V45qEuP1RHuOwRIMv1jdH+OU+K4Jz6xSP+QpkjW6evwxeQK8CSyKlCNcPC4JKT6CMYbfiEQnR9ez7x7w9FwtjATofSvsLGYXu8vB/MYq2/wagtwAwUu9quC5oxksAZHO8DsCoEPnihBF+HtgNec6tCBDb7A4HgVkp2jLlqqeq6VzcvoxskcyRT0cvSl9CjsR08BRwYhOlvzhN62BopoXbRkOoCWPYOc8fb0JwiehmPLhEbwvgWyViu/1sbYuU7cEFZkalld25VGkHahKsssa/ngKYq1DyTjN1WTQUSX8KGKSmhpYRe77f4yQWKTue13SU4GmNYBNjUUUE5729ALRQtEeLIrcGhw2R7GzgPNE6ZHWLCmHJYLrfPWkGh3g0hGZD4tKMWewouGwAxqLyb2G+GY1BKsTQntUmyPETH80e2DuR01LRvFETdEfVhPGfsPE869Me+eacVlmQcSNTu/M/fRyUW8SkfzQHfyS2cbL3AnU10PqjwN4ae43ujBe40bOYjTke9gDXZj8fZuiBLclwr/6XIpZzCU/6GAqb/s=
  - COMMIT=${TRAVIS_COMMIT::8}
  - export TAG=`if [[ $TRAVIS_PULL_REQUEST == "false" ]] && [[ $TRAVIS_BRANCH == "master"
    ]]; then echo "latest"; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi`
  - secure: U9BMheCqO7/oYRVCeyrHKy3Y3xxCsaV+ov6dBMKZHFF8g63OLZhXwpkCkHn0S9OWYfcZaZLyhL5gcI1uc+e2CfUAaQLkS4WpqViV3Q0v5JXs5YjFT5W7u3HvbWMamt5oZ2AgspNEFUrj0bfEJl2aSyDqw/tFCJDJPSIZcFCH9onQWQ1XjDfoB9bGy8WRBXSQHU/a9B+hAzAzZ/NWkAmPepsm2dWrdZFPB6Bd1ZcjjsJBcRx1LVk6BFULdaWjfuFMAEo08Yg9jslNvIrbERI+igKNGWQKf3RobASp6SogE3Z+1oyMbVAwd8oHtEs3DS/z5ZDPVGU/lbIJ1nH3MlgpIxtNzZnHifkeFLGcgOm1JqJhx0xxOPriVmQ0i6QlXJ6yaueisS/SLsTpcygYBvl6NO9ZITCy43N023uxNgT2czq/abtBZfBfgBo4Qe8UCLbyfYmzFGbeVMyZeU6YJw+88H0bt+AMDG05L0hpHwhNgRMCRfO4WkpagNUeTPZpJWKyfBCz+Ym74WBtdASD6KmxWzbLO7QMPVJf5xdPSzRzw7E2nOEk7eLsVofIOTLI2MOrOYCwXTbrzDpkkCAeWbMUweJQMOYHZY5afABdLTrGxQ1sbbA5q6KaBColCZesL7an0vxj2ycOpozcezYttMONjK1EuFIk/mf8IGIoWI9XOyI=

before_install:
  - docker build -t $DOCKER_REPO:$TAG .
  - docker run -d --name rtmp -p 1935:1935 -p 80:80 $DOCKER_REPO
  - docker ps -a

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  - if [[ $TRAVIS_PULL_REQUEST == "false" ]] && [[ $TRAVIS_BRANCH == "master" ]]; then
    docker tag $DOCKER_REPO:$TAG $DOCKER_REPO:$TRAVIS_BUILD_NUMBER;
    docker push $DOCKER_REPO:$TRAVIS_BUILD_NUMBER;
    else
    docker tag $DOCKER_REPO:$TAG $DOCKER_REPO:$COMMIT;
    docker push $DOCKER_REPO:$COMMIT;
    fi
  - docker push $DOCKER_REPO:$TAG;
