sudo: required

language: generic

services:
  - docker

env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - export TAG=`if [[ $TRAVIS_PULL_REQUEST == "false" ]] && [[ $TRAVIS_BRANCH == "master" ]]; then echo "latest"; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi`
  - secure: VJLNnLmR+j/drvCMxgWDHy8TtNhhxXXjU6LLDoovQcrfhAKPPsIqO33b/A+CR6yQEIO4fLSmXWnZbTBafzRue1Xv9XPtLpAEcU3a9JonkDGB3nl+2eDPbXJ2IV5OIxU6CZU4wa2UDZVnVT7yO8vHIuAVWgqInbro1pngGYOlBQBDA8vz/oJexmSNZ7HdSYYh6fv8YIGjhepsE7y372kbZh8i6j1o+59RzG3BabGGOov3SFSGqFNvJfqUsVE4pDMkdp33OxUdQSqVNUNQk/1FQQfITjg3TL0IqC4Yov7dda0wd62jlMKDWT9XZBjKrYrJqmEpHAFFHeM4TOin20+U9saHya/OVVdAFHeAIvVx4TRW3r2N2PIAmtrv0XDjfVQNIJwVQyYitenBMBePc4J2a9vq0SeGthc9YxBFh5h5b06t8s0tH6mlmp33ZEjyzRiTjyAksINAS+02jP9Cr9wEUc3aT5pQPv7pVRjR2pjjh4xpYyT7BUFGKcend7OP0COXNAxn10Um2h0SBpkPhzSM3U4awTEdOOcTamuJr5rUuS5YmIgYJnbj2glEGc7zGUexc1tkib2mm9TGgfR9v9P6WWqbUB1Che/pRtJzVWTPrvtH/0GjPMqHkjl6IpUIqldAvwvayZUV+lm3Bb6K2GtUV7Um/kcwfAKQQ1N5xwC7DdM=
  - secure: kfpd3UZje5Un+0OYny0yi3ZdYPEsTfPtObomx0JnmsEATXRUeXr0TsJX4dtNDP3b43N9zi7HBqYPyPZ1G1Bf28qyKQAxaKXJ12Lix3chFvyzJkgsmGK3l3hi66Co2ulYURtLY7LNGLHlRdYg0/cUEyEblqZu/ZjrPgW9F3x7IXBQnBXZIXpNeXMXTGaBOfCm5cM1rRQjm91z4jmHnGsFPDfAZFU/i/cJEaQF/ZK0cOUvADI5Agg4Km0oWCT1U5vntUBw7kSF8uNw0D+er97EqaQSdnaCQQkQwyyToGWgx9JaKkJFDfH6scGGqLZfvzb86r5hSm2EHPW4swGEyP6KwUL1dPEllufrgfYP7O4+j3QxIcQmNiJWPYSWnFUKrc5tAsbH9jHZDWT22urWlg1BEUL82bmGZQSztuLiUZBU2cZeQiDoluOkhw/3EUewcmC5IQfz5YX7B8hkNC5rQYR0BcMrdniUnlBHlS6DwmLfUx1EnWsAbBvvYk7dmfHAUY4zaHIm6OAw1Ekgf4wx/LYOvwYxmmDhVNhkdDEvLAstL8Spft98kVefsidARJwdF07m9I3buK3upN+Aq2Zrt7oNhg31nNGIk5GFc0yWMWdEV4ZMOOro7G5P6trkAWmNUjseRBfGb1AKVYUMOLj+Ka0kD0asSyA4WK8CTrRmYSLO/X0=
  - secure: tiySUuHahI2/NL4RuqwJoJDPoNI27KE+YbhdQlMeTBzUObnnnS/0jTJzotV6BUqoKnbZedL50F6YzeEKMtsJeseLc5UiOg9lx/BAgd8I5VHb2xHq3JDlrdvLO+lNcu9QS0o1BfqVQhp1GWEStiteFtaDdN4OUC832BoAZFZMsEWycLTsC+QZnSy2So90WzwY9VJM+kXRAIAFwnC1evjv9xTGuGsY0/z0uaBdGCAQsfWl9elIbbdi4VwK0OIchFGIzqj48s+UZ69AinuiioX5lh3ymRZ0PZpSTakIeaX9Fxi9vSGfmoY74JB9Ln0cVVf1Jf6OesJ4nVaU/CQbDnO071qbqi8OtnUVSEUxx4GmeX9uQ7V4xKlVQKyo3dFlt6X17zQXfCLtDtlhS1ZecBNAKXPAg91+jUveFt5FQ3zibwshYE1hLCdYPZFydzQA3tDWbcmR1Nplk7E79G4Euq/NImzGI5U0+yrXEvahr3v6EGPFE/SNLd5ols4Ujt49oxT8oFFbiuveTQN8e7eQy9ju4nGreqGxDe8Sj6JpU8GqfVckPAA7xPh3NC3+wcFZF70n9aRprhRJTJgblozH91ZSj4J7kVCDODiAJR5wSTs3GcIAVCunTP3BcIwL1Sk4WOSd1QX6J3TH97K+pXGW3vfU7tda34TJW3SpQO06PfPe+gM=

before_install:
  - docker build -t $DOCKER_REPO:$TAG .
  - docker run -d --name rtmp -p 1935:1935 -p 80:80 $DOCKER_REPO
  - docker ps -a
after_success:
  - docker login --username="$DOCKER_USERNAME" --password="$DOCKER_PASSWORD";
  - if [[ $TRAVIS_PULL_REQUEST == "false" ]] && [[ $TRAVIS_BRANCH == "master" ]]; then
      docker tag $DOCKER_REPO:$TAG $DOCKER_REPO:$TRAVIS_BUILD_NUMBER; 
      docker push $DOCKER_REPO:$TRAVIS_BUILD_NUMBER;
    else
      docker tag $DOCKER_REPO:$TAG $DOCKER_REPO:$COMMIT; 
      docker push $DOCKER_REPO:$COMMIT;
    fi
  - docker push $DOCKER_REPO:$TAG;
