# enable Docker for your repository
options:
  docker: true

pipelines:
  default:
    - step:
        script:
          - export IMAGE_NAME=peuserik/rtmp:$BITBUCKET_COMMIT
          - docker build -t $IMAGE_NAME .
          # authenticate with the Docker Hub registry
          - docker login --username peuserik --password Borussia1984
          - docker push $IMAGE_NAME
  branches:
    master:
      - step:
          script:
          - export IMAGE_NAME=peuserik/rtmp:latest
          - docker build -t $IMAGE_NAME .
          - docker login --username peuserik --password Borussia1984
          - docker push $IMAGE_NAME
    '*':
      - step:
          script:
          - export IMAGE_NAME=peuserik/rtmp:$BITBUCKET_BRANCH
          - docker build -t $IMAGE_NAME .
          - docker login --username peuserik --password Borussia1984
          - docker push $IMAGE_NAME
