apiVersion: v1
kind: Service
metadata:
  name: rtmp-tv-service
  namespace: rtmp
  labels:
    app: rtmp-tv
spec:
  type: LoadBalancer # use NodePort for our providers
  externalTrafficPolicy: Cluster
#  loadBalancerIP: $(staticIP-from-gce)
  ports:
  - name: rtmp-input
    port: 1935
    targetPort: 1935
    protocol: TCP
  - name: http-port
    port: 80
    protocol: TCP
  - name: https-port
    port: 443
    protocol: TCP
  - name: healthz
    port: 8080
    protocol: TCP
  selector:
    app: rtmp-tv