apiVersion: v1
kind: Service
metadata:
  labels:
    app: rtmp-tv
  name: rtmp-tv-service
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  - name: rtmp
    port: 1935
    protocol: TCP
    targetPort: 1935
  - name: https
    port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app: rtmp-tv
  type: LoadBalancer